services:
  redis:
    image: redis:7-alpine
    container_name: audit-redis
    ports:
      - "6379:6379"
    networks:
      - devintel_net

  engine:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - devintel_net

networks:
  devintel_net:
    external: true